services:
  db:
    image: mongo:latest
    container_name: mflix-db
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
      - ./import:/data/import
    environment:
      MONGO_INITDB_DATABASE: mflix
    networks:
      - ntwrk

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - db
    networks:
      - ntwrk

  app:
    #restart: always #activer uniquement en production
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/mflix
      - PORT=3000
    depends_on:
      - db
    networks:
      - ntwrk
    develop:
      watch:
        - path: ./app
          action: rebuild

networks:
  ntwrk:
